version: '2.1'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "hubadub"
      MYSQL_USER: "danihub"
      MYSQL_PASSWORD: "dani"
      MYSQL_ROOT_PASSWORD: "rootah"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  web:
    build: .
    command: art work
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy