version: '2.1'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "hubadub"
      MYSQL_USER: "danihub"
      MYSQL_PASSWORD: "dani"
      MYSQL_ROOT_PASSWORD: "rootah"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  web:
    build:
      context: .
      args:
        EMAIL_ADDRESS: ${SWANYE_EMAIL_ADDR}
        EMAIL_PASSWORD: ${SWANYE_EMAIL_PSWD}
    command: bash -c "nginx && art work"
    volumes:
      - .:/myapp
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
